### ISSUE TITLE
Should I use this instead of the package from Apollo Server ?

### ISSUE THREAD

**Issue by muco-rolle** [autotelic/apollo-server-fastify#12]
I'm using Fastify v3 and I'm having trouble with apollo-server-fastify to make it work with v3 of fastify should I use this module?

**Comment by HW13** [comment]
Sure, you could use this module - it's essentially a fork of apollo-server-fastify, but with Fastify v3 compatibility. Just a warning though, we'll probably stop maintaining this once apollo-server 3.0 is released - not sure when that will be though.

Alternatively, there is an apollo-server-fastify alpha release that should be Fastify v3 compatible ([here](https://www.npmjs.com/package/apollo-server-fastify/v/3.0.0-alpha.3)).

Another great option for a Fastify v3 GraphQL server is [Mercurius](https://github.com/mercurius-js/mercurius) - it's built and maintained by a lot of the same folks who built and maintain Fastify (so you know it's good 😄 ).
